fn main() {
    #[cfg(windows)]
    {
        // Only set icon if logo.ico exists (generated by CI from logo.png)
        if std::path::Path::new("assets/logo.ico").exists() {
            let mut res = winres::WindowsResource::new();
            res.set_icon("assets/logo.ico");
            if let Err(e) = res.compile() {
                eprintln!("Warning: Failed to set Windows icon: {}", e);
            }
        }
    }
}